class_name LessonCatalog
extends RefCounted
## Training modules and investigation cases. Progress keys are module ids.

static func modules() -> Array[Dictionary]:
	return [
		{
			"id": "mod_01",
			"title": "Phishing & Email Threats",
			"desc": "Identify malicious emails and spoofed senders",
			"accent": "cyan",
		},
		{
			"id": "mod_02",
			"title": "Social Engineering",
			"desc": "Spot impersonation and pressure tactics",
			"accent": "magenta",
		},
		{
			"id": "mod_03",
			"title": "Mobile Threats",
			"desc": "Recognize malicious apps and smishing",
			"accent": "green",
		},
		{
			"id": "mod_04",
			"title": "Workplace Security",
			"desc": "Physical access, tailgating, and clean desks",
			"accent": "cyan",
		},
		{
			"id": "mod_05",
			"title": "OSINT Basics",
			"desc": "What public data reveals about a target",
			"accent": "muted",
		},
	]


static func module_ids() -> Array[String]:
	var ids: Array[String] = []
	var list: Array[Dictionary] = modules()
	for i in list.size():
		ids.append(str(list[i].get("id", "")))
	return ids


static func module_by_id(module_id: String) -> Dictionary:
	var list: Array[Dictionary] = modules()
	for i in list.size():
		if str(list[i].get("id", "")) == module_id:
			return list[i]
	return {}


static func lessons_for(module_id: String) -> Array[Dictionary]:
	match module_id:
		"mod_01":
			return _phishing()
		"mod_02":
			return _social()
		"mod_03":
			return _mobile()
		"mod_04":
			return _workplace()
		"mod_05":
			return _osint()
		_:
			return []


static func lesson_count(module_id: String) -> int:
	return lessons_for(module_id).size()


static func _case(
	case_id: String,
	date: String,
	time: String,
	title: String,
	explain: String,
	body: String,
	evidence: String,
	choices: PackedStringArray,
	correct_choice: int,
	flags: PackedStringArray,
	correct_flags: PackedInt32Array
) -> Dictionary:
	return {
		"case_id": case_id,
		"date": date,
		"time": time,
		"title": title,
		"explain": explain,
		"body": body,
		"evidence": evidence,
		"choices": choices,
		"correct_choice": correct_choice,
		"flags": flags,
		"correct_flags": correct_flags,
	}


static func _phishing() -> Array[Dictionary]:
	return [
		_case("MAIL-01", "03/11/2026", "08:14AM", "PAYROLL RESET",
			"PHISHING FAKES A TRUSTED SENDER. CHECK THE REAL DOMAIN LETTER BY LETTER AND HOVER LINKS BEFORE YOU TYPE A PASSWORD. HR WILL NOT RESET PAYROLL ON A LOOKALIKE SITE.",
			"AN EMAIL SAYS HR RESET YOUR PAYROLL PASSWORD. THE SENDER IS HR-TEAM@LEVELBLUE.CO. THE LINK GOES TO LEVELBLUE-PAY.WEB.APP.",
			"envelope",
			PackedStringArray(["LEGITIMATE HR MAIL", "PHISHING / SPOOFED SENDER", "INTERNAL SPAM"]),
			1,
			PackedStringArray(["SENDER DOMAIN IS NOT OURS", "LINK DOES NOT MATCH OUR SITE"]),
			PackedInt32Array([0, 1])),
		_case("MAIL-02", "03/12/2026", "07:02AM", "CEO WIRE REQUEST",
			"BUSINESS EMAIL COMPROMISE IMPERSONATES A LEADER AND DEMANDS FAST MONEY MOVEMENT. REAL EXECUTIVES USE OFFICIAL ADDRESSES AND A SECOND APPROVAL CHANNEL. URGENCY IS THE BAIT.",
			"A MESSAGE FROM THE CEO ASKS YOU TO WIRE FUNDS BEFORE STAND-UP. THE TONE IS URGENT. THE ADDRESS IS A PUBLIC GMAIL ACCOUNT.",
			"envelope",
			PackedStringArray(["REAL EXECUTIVE ORDER", "BEC / IMPERSONATION", "CALENDAR REMINDER"]),
			1,
			PackedStringArray(["URGENCY IS USED TO SKIP CHECKS", "SENDER IS NOT A COMPANY ADDRESS"]),
			PackedInt32Array([0, 1])),
		_case("MAIL-03", "04/02/2026", "11:40AM", "VENDOR INVOICE",
			"MALWARE HIDES IN ATTACHMENTS. A DOUBLE EXTENSION LIKE .EXE.PDF MEANS WINDOWS MAY RUN CODE, NOT OPEN A BILL. NEVER ENABLE MACROS FROM EMAIL.",
			"A PDF INVOICE ARRIVES FROM A KNOWN VENDOR. THE ATTACHMENT NAME IS INVOICE_FINAL.EXE.PDF. MACRO PROMPTS APPEAR ON OPEN.",
			"terminal",
			PackedStringArray(["NORMAL BILLING", "MALICIOUS ATTACHMENT", "SCANNER GLITCH"]),
			1,
			PackedStringArray(["DOUBLE EXTENSION HIDES AN EXECUTABLE", "MACROS SHOULD NOT AUTO-RUN"]),
			PackedInt32Array([0, 1])),
		_case("MAIL-04", "04/18/2026", "03:21PM", "PACKAGE TRACKING",
			"DELIVERY SCAMS STEAL LOGINS WITH FAKE TRACKING PAGES. IF YOU DID NOT ORDER ANYTHING, DELETE IT. REAL CARRIERS USE HTTPS ON THEIR REAL DOMAIN.",
			"A SHIPPING ALERT SAYS A PARCEL IS HELD. THE LINK USES HTTP AND A RANDOM SUBDOMAIN. YOU DID NOT ORDER ANYTHING.",
			"envelope",
			PackedStringArray(["REAL CARRIER NOTICE", "CREDENTIAL HARVEST PAGE", "IT MAINTENANCE MAIL"]),
			1,
			PackedStringArray(["YOU DID NOT PLACE AN ORDER", "THE LINK IS NOT HTTPS ON THE REAL DOMAIN"]),
			PackedInt32Array([0, 1])),
		_case("MAIL-05", "05/01/2026", "09:05AM", "PASSWORD EXPIRY",
			"LOOKALIKE DOMAINS SWAP ONE LETTER TO STEAL CREDENTIALS. IT NEVER ASKS FOR YOUR PASSWORD BY EMAIL. USE THE BOOKMARKED PORTAL INSTEAD.",
			"A BANNER SAYS YOUR PASSWORD EXPIRES IN 30 MINUTES. IT ASKS YOU TO RE-ENTER IT ON A LOOKALIKE PORTAL WITH ONE LETTER SWAPPED.",
			"terminal",
			PackedStringArray(["DIRECTORY POLICY MAIL", "FAKE LOGIN PORTAL", "VPN OUTAGE NOTE"]),
			1,
			PackedStringArray(["DOMAIN USES A LOOKALIKE LETTER", "IT WOULD NEVER ASK FOR YOUR PASSWORD BY MAIL"]),
			PackedInt32Array([0, 1])),
		_case("MAIL-06", "05/09/2026", "04:55PM", "SHARED DOCUMENT",
			"FILE SHARES SHOULD STAY IN THE COMPANY TENANT. A PERSONAL DRIVE PLUS AN UNKNOWN EDITOR IS A COMMON WAY TO EXFILTRATE DATA. VERIFY THE OWNER FIRST.",
			"A COLLABORATOR SHARES A BUDGET SHEET. THE SHARE LINK IS FROM A PERSONAL DRIVE, NOT THE COMPANY TENANT. EDIT ACCESS IS REQUESTED.",
			"envelope",
			PackedStringArray(["SAFE INTERNAL SHARE", "UNTRUSTED SHARE LINK", "PRINTER QUEUE ALERT"]),
			1,
			PackedStringArray(["FILE IS OUTSIDE THE COMPANY TENANT", "UNKNOWN ACCOUNT REQUESTS EDIT ACCESS"]),
			PackedInt32Array([0, 1])),
	]


static func _social() -> Array[Dictionary]:
	return [
		_case("SOC-01", "02/14/2026", "10:11AM", "HELP DESK CALLBACK",
			"VISHING IS PHISHING BY PHONE. IT WILL NEVER ASK FOR YOUR OTP. CALLER ID CAN BE FAKED. HANG UP AND CALL THE NUMBER IN THE DIRECTORY.",
			"A CALLER SAYS THEY ARE IT AND NEED YOUR OTP TO UNLOCK YOUR ACCOUNT. THEY KNOW YOUR DESK NUMBER AND SOUND CALM.",
			"phone",
			PackedStringArray(["NORMAL IT SUPPORT", "VISHING / OTP THEFT", "BUILDING MAINTENANCE"]),
			1,
			PackedStringArray(["IT WILL NEVER ASK FOR YOUR OTP", "CALLER-ID CAN BE SPOOFED"]),
			PackedInt32Array([0, 1])),
		_case("SOC-02", "02/20/2026", "01:30PM", "NEW VENDOR ACCOUNT",
			"INVOICE REDIRECT FRAUD CHANGES WHERE MONEY GOES. BANK DETAILS ONLY CHANGE THROUGH A VERIFIED SECOND CHANNEL. URGENCY IS THERE TO SKIP POLICY.",
			"A SUPPLIER EMAILS A NEW BANK ACCOUNT FOR INVOICES. THEY ASK YOU TO UPDATE IT TODAY SO PAYMENTS ARE NOT DELAYED.",
			"envelope",
			PackedStringArray(["ROUTINE ACCOUNT CHANGE", "INVOICE REDIRECT FRAUD", "TAX FORM UPDATE"]),
			1,
			PackedStringArray(["BANK CHANGES NEED A SECOND CHANNEL", "URGENCY PUSHES YOU PAST POLICY"]),
			PackedInt32Array([0, 1])),
		_case("SOC-03", "03/03/2026", "06:44PM", "PRESSURE FROM A STRANGER",
			"SOCIAL PRESSURE SCAMS ASK YOU TO KEEP A SECRET AND PAY WITH GIFT CARDS. REAL CLIENT GIFTS GO THROUGH FINANCE. SECRECY PLUS GIFT CARDS IS A HARD NO.",
			"A NEW CONTACT ASKS YOU TO BUY GIFT CARDS FOR A CONFIDENTIAL CLIENT GIFT. THEY SAY LEGAL CANNOT KNOW YET.",
			"phone",
			PackedStringArray(["APPROVED CLIENT GIFT", "SOCIAL PRESSURE SCAM", "TRAVEL BOOKING"]),
			1,
			PackedStringArray(["SECRECY IS A RED FLAG", "GIFT CARDS ARE A COMMON PAYOUT"]),
			PackedInt32Array([0, 1])),
		_case("SOC-04", "03/22/2026", "09:18AM", "FAKE AUDITOR",
			"IMPERSONATION AT THE DOOR RELIES ON A LANYARD AND CONFIDENCE. SURPRISE AUDITS STILL HAVE TICKETS AND ESCORTS. NO BADGE, NO ENTRY.",
			"SOMEONE IN A LANYARD ASKS TO TAILGATE INTO THE SOC FOR A SURPRISE AUDIT. THEY HAVE NO ESCORT AND NO TICKET NUMBER.",
			"badge",
			PackedStringArray(["VALID SURPRISE AUDIT", "IMPERSONATION AT THE DOOR", "FIRE DRILL"]),
			1,
			PackedStringArray(["NO ESCORT AND NO TICKET", "AUDITS ARE SCHEDULED IN WRITING"]),
			PackedInt32Array([0, 1])),
		_case("SOC-05", "04/07/2026", "02:05PM", "PRETEXT ON SLACK",
			"PRETEXTING BORROWS A TRUSTED NAME. DISPLAY NAMES ON CHAT ARE EASY TO FAKE. PAYMENT APPROVALS STAY ON THE REAL CHANNEL WITH THE REAL PERSON.",
			"A SLACK DM FROM A LOOKALIKE DISPLAY NAME ASKS YOU TO APPROVE A PAYMENT WHILE YOUR MANAGER IS IN THE AIR.",
			"terminal",
			PackedStringArray(["REAL MANAGER PING", "PRETEXTING ON CHAT", "STATUS BOT"]),
			1,
			PackedStringArray(["DISPLAY NAME CAN BE FAKED", "PAYMENT APPROVAL NEEDS THE REAL CHANNEL"]),
			PackedInt32Array([0, 1])),
		_case("SOC-06", "04/28/2026", "11:50AM", "RECRUITER LINK",
			"A JOB PITCH CAN STILL BE A CREDENTIAL TRAP. COMPANY SSO SHOULD ONLY APPEAR ON COMPANY SITES. IF THEY ASK YOU TO SKIP IT, STOP.",
			"A RECRUITER SENDS A JOB BRIEF AND ASKS YOU TO OPEN A PORTFOLIO SITE THAT REQUESTS COMPANY SSO.",
			"envelope",
			PackedStringArray(["NORMAL RECRUITING", "CREDENTIAL PHISH VIA PRETEXT", "BENEFITS ENROLLMENT"]),
			1,
			PackedStringArray(["SSO PROMPT ON A THIRD-PARTY SITE", "THEY ASKED YOU TO SKIP IT SECURITY"]),
			PackedInt32Array([0, 1])),
	]


static func _mobile() -> Array[Dictionary]:
	return [
		_case("MOB-01", "01/09/2026", "08:40AM", "SIDELOADED APK",
			"APPS SHOULD COME FROM THE OFFICIAL STORE. A DM WITH AN APK PLUS UNKNOWN SOURCES IS HOW MALWARE GETS A FOOTHOLD. DO NOT INSTALL IT.",
			"A COWORKER SENDS A CHAT APP APK IN A DM. THEY SAY THE STORE VERSION IS BROKEN. INSTALL UNKNOWN SOURCES IS REQUIRED.",
			"phone",
			PackedStringArray(["HELPFUL INTERNAL BUILD", "MALICIOUS SIDELOAD", "OS UPDATE"]),
			1,
			PackedStringArray(["APK DID NOT COME FROM THE STORE", "UNKNOWN SOURCES IS A HIGH-RISK TOGGLE"]),
			PackedInt32Array([0, 1])),
		_case("MOB-02", "01/19/2026", "07:12PM", "SMISHING OTP",
			"SMISHING IS PHISHING BY TEXT. BANKS NEVER ASK YOU TO FORWARD AN OTP. IF A CODE ARRIVES FOR A LOGIN YOU DID NOT START, IGNORE THE TEXT.",
			"A TEXT SAYS YOUR BANK LOCKED THE APP. IT ASKS YOU TO REPLY WITH THE SIX-DIGIT CODE THAT JUST ARRIVED.",
			"phone",
			PackedStringArray(["BANK FRAUD DESK", "OTP INTERCEPT SCAM", "CARRIER NOTICE"]),
			1,
			PackedStringArray(["BANKS DO NOT ASK FOR OTP BY SMS", "THE FIRST CODE WAS FOR A LOGIN YOU DID NOT START"]),
			PackedInt32Array([0, 1])),
		_case("MOB-03", "02/03/2026", "12:08PM", "FAKE WIFI PORTAL",
			"CAPTIVE PORTALS CAN ASK YOU TO ACCEPT TERMS. THEY SHOULD NEVER TAKE YOUR WORK PASSWORD. USE THE COMPANY VPN ON UNTRUSTED WIFI.",
			"AIRPORT WIFI OPENS A PORTAL THAT ASKS FOR YOUR WORK EMAIL AND PASSWORD TO GET ONLINE.",
			"terminal",
			PackedStringArray(["NORMAL CAPTIVE PORTAL", "CREDENTIAL HARVEST HOTSPOT", "VPN LICENSE FORM"]),
			1,
			PackedStringArray(["CAPTIVE PORTALS SHOULD NOT TAKE WORK PASSWORDS", "USE THE COMPANY VPN INSTEAD"]),
			PackedInt32Array([0, 1])),
		_case("MOB-04", "02/16/2026", "09:33AM", "OVERLAY PROMPT",
			"OVERLAY MALWARE DRAWS A FAKE LOGIN ON TOP OF A REAL APP. IF A SECOND SHEET HIDES THE ADDRESS BAR, CLOSE THE APP AND CHECK THE ICON.",
			"RIGHT AFTER A BANK APP OPENS, A SECOND LOGIN SHEET APPEARS. THE ADDRESS BAR IS HIDDEN. THE ICON LOOKS SLIGHTLY OFF.",
			"phone",
			PackedStringArray(["BANK APP REDESIGN", "OVERLAY / FAKE PROMPT", "BIOMETRIC TIMEOUT"]),
			1,
			PackedStringArray(["A SECOND SHEET HID THE REAL APP", "THE ICON DOES NOT MATCH THE STORE LISTING"]),
			PackedInt32Array([0, 1])),
		_case("MOB-05", "03/01/2026", "05:20PM", "PARKING QR",
			"ATTACKERS STICK FAKE QR CODES OVER REAL ONES. SHORT LINKS HIDE THE HOST. PAY ONLY THROUGH THE OFFICIAL METER APP OR KIOSK.",
			"A STICKER ON A METER SAYS PAY HERE AND SHOWS A QR CODE. THE URL IS A SHORT LINK TO A FORM ASKING FOR CARD DETAILS.",
			"camera",
			PackedStringArray(["CITY PAYMENT KIOSK", "QR CODE SWAP", "LOYALTY SIGNUP"]),
			1,
			PackedStringArray(["STICKER CAN COVER THE REAL CODE", "SHORT LINKS HIDE THE REAL HOST"]),
			PackedInt32Array([0, 1])),
		_case("MOB-06", "03/15/2026", "10:02AM", "CAMERA PERMISSION",
			"APPS SHOULD ASK ONLY FOR WHAT THEY NEED. A FLASHLIGHT THAT WANTS CONTACTS AND SMS IS SPYWARE BEHAVIOR. DENY AND UNINSTALL.",
			"A FLASHLIGHT APP DEMANDS CAMERA, CONTACTS, AND SMS ON FIRST LAUNCH. IT WILL NOT TURN ON THE LIGHT WITHOUT THEM.",
			"phone",
			PackedStringArray(["NORMAL PERMISSION SET", "OVER-SCOPED SPYWARE RISK", "ACCESSIBILITY TOOL"]),
			1,
			PackedStringArray(["A FLASHLIGHT DOES NOT NEED CONTACTS OR SMS", "DENY AND UNINSTALL"]),
			PackedInt32Array([0, 1])),
	]


static func _workplace() -> Array[Dictionary]:
	return [
		_case("SITE-01", "01/12/2026", "08:02AM", "TAILGATE AT THE DOOR",
			"TAILGATING IS FOLLOWING SOMEONE THROUGH A CONTROLLED DOOR. COURTESY IS NOT ACCESS. EVERY PERSON SWIPES THEIR OWN BADGE. SEND STRANGERS TO RECEPTION.",
			"A PERSON WITH COFFEE AND A SMILE FOLLOWS YOU THROUGH THE BADGE READER. THEY SAY THEY FORGOT THEIR PASS AT THE CAR.",
			"badge",
			PackedStringArray(["HARMLESS COURTESY", "TAILGATING ATTEMPT", "FIRE EXIT DRILL"]),
			1,
			PackedStringArray(["EVERY PERSON NEEDS THEIR OWN BADGE", "SEND THEM TO RECEPTION"]),
			PackedInt32Array([0, 1])),
		_case("SITE-02", "01/27/2026", "06:50PM", "CLEAN DESK FAIL",
			"CLEAN DESK MEANS NO SECRETS LEFT IN THE OPEN. LOCK THE SESSION WHEN YOU STAND UP. PASSWORDS NEVER GO ON STICKY NOTES.",
			"A STICKY NOTE ON A MONITOR HAS A VPN PASSWORD. THE LAPTOP IS UNLOCKED. THE OWNER STEPPED OUT FOR TEN MINUTES.",
			"terminal",
			PackedStringArray(["FINE FOR A SHORT BREAK", "CREDENTIAL EXPOSURE", "APPROVED SHARED DESK"]),
			1,
			PackedStringArray(["PASSWORDS MUST NOT BE WRITTEN ON THE DESK", "LOCK THE SESSION WHEN YOU LEAVE"]),
			PackedInt32Array([0, 1])),
		_case("SITE-03", "02/08/2026", "09:15AM", "USB IN THE LOT",
			"A LABELED USB IN A PARKING LOT IS A CLASSIC BAIT DROP. PLUGGING IT IN CAN RUN MALWARE. SEAL IT AND HAND IT TO SECURITY.",
			"A USB STICK LABELED PAYROLL-2026 SITS BY THE STAFF ENTRANCE. NOBODY CLAIMS IT.",
			"terminal",
			PackedStringArray(["LOST STAFF DRIVE", "BAIT DROP / MALWARE", "PRINTER SPOOL"]),
			1,
			PackedStringArray(["DO NOT PLUG IN UNKNOWN MEDIA", "HAND IT TO SECURITY, SEALED"]),
			PackedInt32Array([0, 1])),
		_case("SITE-04", "02/24/2026", "01:12PM", "SHOULDER SURF",
			"SHOULDER SURFING IS WATCHING YOU TYPE A CODE. SHIELD THE PAD AND ASK STRANGERS TO STEP BACK. PINS ARE NOT PUBLIC.",
			"SOMEONE STANDS CLOSE BEHIND YOU AT THE LOBBY KIOSK WHILE YOU TYPE A VISITOR CODE. THEY ARE NOT ON YOUR MEETING.",
			"camera",
			PackedStringArray(["WAITING FOR THE ELEVATOR", "SHOULDER SURFING", "PHOTO FOR THE NEWSLETTER"]),
			1,
			PackedStringArray(["SHIELD THE PIN PAD", "ASK THEM TO STEP BACK"]),
			PackedInt32Array([0, 1])),
		_case("SITE-05", "03/10/2026", "04:40PM", "PRINTER TRAY",
			"PRINTERS HOLD BADGES, PINS, AND PHOTOS. UNATTENDED OUTPUT IS A LEAK. COLLECT IT OR SHRED IT THE MOMENT IT LANDS.",
			"A STACK OF BADGE REQUEST FORMS SITS IN THE PRINTER. NAMES, PHOTOS, AND TEMPORARY PINS ARE VISIBLE.",
			"badge",
			PackedStringArray(["READY FOR PICKUP", "UNATTENDED SENSITIVE PRINT", "RECYCLING BIN"]),
			1,
			PackedStringArray(["PINS AND PHOTOS ARE SENSITIVE", "COLLECT OR SHRED IMMEDIATELY"]),
			PackedInt32Array([0, 1])),
		_case("SITE-06", "03/29/2026", "11:05AM", "VISITOR BADGE",
			"VISITORS NEED A VALID BADGE AND AN ESCORT. EXPIRED LOBBY-ONLY ACCESS IS NOT A TOUR PASS. STOP THEM AND CALL RECEPTION.",
			"A VISITOR WALKS THE FLOOR WITHOUT AN ESCORT. THEIR BADGE SAYS LOBBY ONLY AND EXPIRED YESTERDAY.",
			"badge",
			PackedStringArray(["SELF-GUIDED TOUR", "UNESCORTED EXPIRED VISITOR", "NEW HIRE ORIENTATION"]),
			1,
			PackedStringArray(["EXPIRED BADGE IS NOT ACCESS", "STOP AND CALL RECEPTION"]),
			PackedInt32Array([0, 1])),
	]


static func _osint() -> Array[Dictionary]:
	return [
		_case("OSINT-01", "01/05/2026", "03:00PM", "OVERSHARING A ROLE",
			"OSINT IS INTEL FROM PUBLIC POSTS. SHIFT TIMES AND INTERNAL TOOL NAMES HELP AN ATTACKER PLAN. KEEP OPERATIONS DETAILS OFF SOCIAL PROFILES.",
			"A PUBLIC PROFILE LISTS SHIFT TIMES, BADGE COLOR, AND THE NAME OF THE SOC TOOLING STACK.",
			"badge",
			PackedStringArray(["GOOD RECRUITING DETAIL", "OPSEC LEAK", "REQUIRED JOB POST"]),
			1,
			PackedStringArray(["SHIFT TIMES HELP AN ATTACKER PLAN", "INTERNAL TOOL NAMES SHOULD STAY INTERNAL"]),
			PackedInt32Array([0, 1])),
		_case("OSINT-02", "01/21/2026", "05:45PM", "PHOTO GEOTAG",
			"PHOTOS CAN CARRY GPS AND SHOW DOORS. STRIP GEOTAGS BEFORE YOU POST. DO NOT PUBLISH A MAP OF THE BUILDING ENTRANCE.",
			"A TEAM SELFIE FROM THE ROOF STILL HAS GPS IN THE FILE. THE BUILDING ENTRANCE IS IN FRAME.",
			"camera",
			PackedStringArray(["HARMLESS TEAM PHOTO", "LOCATION DISCLOSURE", "APPROVED PRESS KIT"]),
			1,
			PackedStringArray(["STRIP GEOTAGS BEFORE POSTING", "ENTRANCES SHOULD NOT BE MAPPED IN PUBLIC"]),
			PackedInt32Array([0, 1])),
		_case("OSINT-03", "02/06/2026", "08:22AM", "PASSWORD FROM LIFE",
			"SECRETS BUILT FROM A PET NAME AND A GRAD YEAR ARE PUBLIC. ATTACKERS READ BIOS. NEVER PHOTO A PASSWORD HINT.",
			"A BIO MENTIONS A PET NAME AND A GRAD YEAR. THE SAME STRING IS USED AS A WIFI HINT ON A STICKY IN A DESK PHOTO.",
			"envelope",
			PackedStringArray(["STRONG PERSONAL PASSPHRASE", "RECONSTRUCTABLE SECRET", "RANDOM GENERATOR"]),
			1,
			PackedStringArray(["PUBLIC FACTS ARE NOT SECRETS", "DO NOT PHOTO PASSWORD HINTS"]),
			PackedInt32Array([0, 1])),
		_case("OSINT-04", "02/19/2026", "12:30PM", "JOB POST LEAK",
			"JOB ADS SHOULD NOT LIST HOSTNAMES OR FIREWALL VERSIONS. THOSE STRINGS FEED EXPLOIT SEARCHES. KEEP INFRASTRUCTURE INTERNAL.",
			"A HIRING AD LISTS INTERNAL HOSTNAMES AND THE EXACT VERSION OF THE FIREWALL.",
			"terminal",
			PackedStringArray(["HELPFUL FOR CANDIDATES", "INFRASTRUCTURE DISCLOSURE", "SALARY BAND NOTE"]),
			1,
			PackedStringArray(["VERSION STRINGS AID EXPLOIT SEARCH", "KEEP HOSTNAMES OFF PUBLIC ADS"]),
			PackedInt32Array([0, 1])),
		_case("OSINT-05", "03/08/2026", "09:10PM", "PASTEBIN DUMP",
			"STAGING KEYS ARE STILL KEYS. A PUBLIC PASTE IS A BREACH UNTIL THEY ARE ROTATED. REVOKE FIRST, THEN ASK WHY IT WAS PASTED.",
			"A PASTE TITLED LEVELBLUE-TEST CONTAINS API KEYS AND A COMMENT THIS IS JUST STAGING.",
			"terminal",
			PackedStringArray(["SAFE BECAUSE IT IS STAGING", "EXPOSED SECRET MATERIAL", "PUBLIC CHANGELOG"]),
			1,
			PackedStringArray(["STAGING KEYS STILL GRANT ACCESS", "REVOKE AND ROTATE AT ONCE"]),
			PackedInt32Array([0, 1])),
		_case("OSINT-06", "03/25/2026", "10:48AM", "BADGE PHOTO",
			"A SHARP PHOTO OF A BADGE CAN BE CLONED. CROP OR BLUR BARCODES AND FULL NAMES BEFORE A POST GOES LIVE.",
			"A CONFERENCE PHOTO ZOOMS TO A READABLE BADGE BARCODE AND THE WEARER'S FULL NAME.",
			"camera",
			PackedStringArray(["FINE FOR SOCIAL POSTS", "BADGE RECON RISK", "REQUIRED SPEAKER SHOT"]),
			1,
			PackedStringArray(["BARCODES CAN BE CLONED FROM PHOTOS", "CROP OR BLUR CREDENTIALS"]),
			PackedInt32Array([0, 1])),
	]
